language: ruby
rvm:
- 2.5
- 2.6
sudo: false
cache: bundler
before_script: bundle update
script:
- bundle exec rake test
notifications:
  slack:
    rooms:
      secure: lh85V1Xmw/vnLCqMi+ndKJ2txLyg38ZZRFmBezo9t6N48FWoJVsjdQzZdsU8GDJL48Bt3/HslMfA2xj2G6WcrorDXkP3BgilQyYvPEaPl93ewgnT+c9mdn+M16pbL/Tt2PZC0ORUkN+aM8svHq3aCLF6X2uwEjVT9Nim6cAjPdf/Dg2D20JAsRa6NmXqCDHa4/w1PbQm2hIKkd3ajllYsD+NVw4miBXp+hK0GMEu7DDJctvRZZUiVHjUgWbusWTkHFX63NSv47BeyTrGAmJdcD5gUH+BOPnrqbWEItBgpxCB1z2+k+X1DwZNPLZrzKytC9nUMEuYZuII1fwFx4y2LONFSThPIKfk7hPRJKD+lK4g592QbFGDhbe5e1rs77Q9dw6bBUzXqEBl1MhdQcC+BebNfcpxu+IlGKVD6Wd3haLQKrJR9uOMSDOvwcedYZAwwcrAwn1tDqsAFZsd2qeAJAuYUhx3vj5v1UFvCs81CU9fWQAQ/WU22hdFDZ9vaB9LYqfFidNYFeZXtrVS2Kv7UZfaPlhB/WNvthdY42oVnLDz6dJ3aYhJ87T5prTBq/1bv3QIi+XeNQcRAS4pCtfsuW0j1NEJrRFC7b4q672BaY4ySQ81EmD5pS+Pm9sW6pvPpAM5vlQnjMIPu7RSg06MpO6UbbXXPLsH0W8Rt7XJDp0=
